### ISSUE TITLE
How to Compile Latest SIGSRF Code using rar packages 

### ISSUE THREAD

**Issue by TahirAbbass** [signalogic/SigSRF_SDK#5]
Hi, I am using "mediaMin" to convert pcaps to wav files. 

I saw that recently in SIGSRF repo commit a AMR\EVS issue was fixed, I think I was getting a segmentation fault because of it in some scenarios, therefore I want to use the latest code to try. 

I am installing SIGSRF using rar package, mainly to use "mediaMin" exe, but I see that rar file "Signalogic_sw_host_SigSRF_SDK_Ubuntu12.04-22.04_27Apr24.rar" is of April 2024, and not upated by latest code.

Can you kindly let me know **How i can get the rar file from latest code?**, or share steps with me to do manually. I was not able to find figure out from the documentation in the Readme files. I checked the installer notes.

Also i get segmentation fault for "mediaMin" when trying to convert EVS 23.85 pcap to wav file, by using following command:

 mediaMin -cx86 -ievs.pcap -d0xc11 -r0.5 -C/home/coder/config/EVS
 
 I have attached the segmentation fault log.
 
 [mediaMin Log file -segmentation fault.log](https://github.com/user-attachments/files/16451843/mediaMin.Log.file.-segmentation.fault.log)
 

Thanks.

**Comment by signalogic** [comment]
Hi Tahir, with mediaMin 3.6.2 I ran this command line **

  mediaMin -cx86 -i../test_files/evs7.pcap -L -d0x08000c11 -r20 -g /tmp/shared -C../session_config/EVS_AMR-WB_IO_mode_payload_shift

and got clear and intelligible speech. mediaMin correctly detects AMR-WB IO 23.85 bps, as you mention. I will e-mail the mediaMin console log and generated/merged stream pcap to you. You can remove the uploaded pcap if you feel it contains proprietary info.

Your mediaMin version is 3.4.2 so considerably older. In the next few days we plan to update Docker containers (Ubuntu, CentOS, and Debian) and about 2 weeks after that Rar packages. Does that work for you ? If not let me know, thanks

** I used the config file "EVS_AMR-WB_IO_mode_payload_shift" as I'm assuming your config file also specifies an AMR-WB IO mode payload shift, per the earlier discussion with Syed Ahmad-Maaz

Also remember to do:

  rm /dev/shm/hwlib*

after a mediaMin seg fault, before running mediaMin again

**Comment by signalogic** [comment]
Hi Tahir, both Docker containers and Rar packages are updated. Please run the above command line (adjusting for file paths) and let me know if it works, thanks

**Comment by TahirAbbass** [comment]
Sure, thanks for the quick update, I am working on testing my pcaps scenarios. I will update you soon if all pcaps works as expected. I think i needed to do this after segmentation fault, which was causing me issue:
rm /dev/shm/hwlib*

Also, I have read the previous issue created by Syed Ahmad-Maaz, it mentions two bit left shift to do, Can i ask for understanding what bits of pcap\bitstream file are left shifted by -d0x08000c11 in mediaMin, unless ofcourse it is proprietary info.

Thanks for help anyway, Will update you soon.

**Comment by signalogic** [comment]
Hi Tahir, shifting of codec payloads is handled in a config file, not by -dN options. We put it in a config file because it's a very uncommon to need to do that. For the EVS AMR-WB IO compatibility mode case you are encountering, the "payload_shift" field in the config file specifies each received payload is left-shifted 2 bits before being given to [DSCodecDecode()](https://github.com/signalogic/SigSRF_SDK/blob/master/codecs_readme.md#dscodecdecode).

As to why this is needed, as I explained to Syed:

"It seems an endpoint or SBC-type entity out there has incorrectly implemented EVS AMR-WB IO payload encoding. We're not sure who yet, but counting your example we've now seen it half a dozen times or so. Maybe they are translating AMR-WB payloads into EVS compatibility mode and somehow misinterpreted the EVS spec, which is admittedly complicated when it comes to AMR-WB IO payload formatting. My guess is that in their internal testing they missed this bug because it's in their EVS common library so it's shared by both their encoder and decoder, but when in the wild other decoders can "see" it"

Please let me know when there are more questions.

**Comment by TahirAbbass** [comment]
Hey, thanks for the update. After some research, i started using official EVS decoder in VOIP mode, which takes rtp dump as input, in comparison to EVS decoder in bit stream mode, which was taking G.192 format bit stream file as input for decoding. Now converting our EVS 23.85 pcap to rtp dump format (as we have in wireshark), and then using official EVS decoder in VoIP mode, gives us correct audio. This was a separate solution from SIGSRF mediaMin utility which we were using.

Thanks for the help. I am marking the issue as done.

**Comment by signalogic** [comment]
Hi Tahir, really nice work !  Can I ask if you can send me one of your 23.85 kbps .rtp files, I'd like to see if the 2-bit payload shift is in there or it got corrected by Wireshark output. I suspect not, which means the correction happens in the reference EVS decoder input from .rtp. If that's the case, it could explain why we are seeing this bug in customer pcaps "in the wild". You can email it to jbrower at signalogic dot com, thanks
